---
# =============================================================================
# NPM Role - Handlers
# =============================================================================

- name: Restart openresty
  ansible.builtin.systemd:
    name: openresty
    state: restarted
    daemon_reload: true

- name: Restart npm
  ansible.builtin.systemd:
    name: npm
    state: restarted
    daemon_reload: true

- name: Enable openresty
  ansible.builtin.systemd:
    name: openresty
    enabled: true
    state: started

- name: Enable npm
  ansible.builtin.systemd:
    name: npm
    enabled: true
    state: started
