---
- name: Set default target to graphical
  ansible.builtin.command: systemctl set-default graphical.target
  changed_when: true

- name: Enable and start LightDM
  ansible.builtin.service:
    name: lightdm
    state: started
    enabled: true
